# Generated by Django 3.2.9 on 2021-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiciosSPA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
