# Generated by Django 3.2.9 on 2021-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiciosSPA', '0002_servicio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
